language: rust

rust:
    - stable
    - beta
    - nightly

install:
    - sudo apt-get install socat

script:
    - cd Rust/pi
    - sudo socat /dev/ptyS10 /dev/ptyS11
    - ls /dev/
    - cargo build --verbose --all
    - sudo cargo test --verbose --all
