language: rust

rust:
    - stable
    - beta
    - nightly

install:
    - sudo apt-get install socat

script:
    - cd Rust/pi
    - sudo socat /dev/ptyS10/dev/ptyS11
    - cargo build --verbose --all
    - cargo test --verbose --all
