language: rust

rust:
    - stable
    - beta
    - nightly

install:
    - sudo apt-get install socat

script:
    - sudo socat /dev/ttyAMA0 /dev/ttyAMA1
    - cargo build --verbose --all
    - cargo test --verbose --all
