language: rust

rust:
    - stable
    - beta
    - nightly

install:
    - sudo apt-get install socat

script:
    - cd Rust/pi
    - sudo socat PTY,link=/dev/ptyS10 PTY,link=/dev/ptyS11 &
    - sudo chown travis:$travis /dev/ptyS10
    - sudo chown travis:travis /dev/ptyS11
    - ls /dev/
    - cargo build --verbose --all
    - cargo test --verbose --all
