language: rust

sudo: true

rust:
    - stable
    - beta
    - nightly

install:
    - apt-get install socat

script:
    - cd Rust/pi
    - socat /dev/ptyS10 /dev/ptyS11
    - ls /dev/
    - cargo build --verbose --all
    - cargo test --verbose --all
