language: rust

rust:
    - stable
    - beta
    - nightly

install:
    - sudo apt-get install socat

script:
    - cd Rust/pi
    - travis-user=$(whoami)
    - sudo socat /dev/ptyS10 /dev/ptyS11
    - sudo chown $travis-user:$travis-user /dev/ptyS10
    - sudo chown $travis-user:$travis-user /dev/ptyS11
    - ls /dev/
    - cargo build --verbose --all
    - cargo test --verbose --all
